### ISSUE TITLE
MainActivity设置有android:launchMode="singleTask" 切换语言后App直接关闭不会 重启 这个要怎么解决好？

### ISSUE THREAD

**Issue by yk007** [getActivity/MultiLanguages#10]

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/117926982-28d65480-b32c-11eb-8776-47e83dc2f029.png)

**Comment by getActivity** [comment]
小伙子，你确定这三种方式都用过了？

**Comment by yk007** [comment]
现在用的第一张方式，会卡顿一下

**Comment by getActivity** [comment]
小伙子，其他方式你也试过了？

**Comment by yk007** [comment]
都试过，切换语言在首页，而首页设置了栈内单例模式后其他2中方式不会重启，需要手动启动一下，第一种用着还好可以满足要求

**Comment by getActivity** [comment]
OK 的，小伙子，你先用着，如果后续你发现了更好的重启方式欢迎反馈给我，我经过核实之后会在 Demo 中注明。
