### ISSUE TITLE
APP小退后切换语言无效

### ISSUE THREAD

**Issue by ender115** [getActivity/MultiLanguages#11]
你好，APP小退后，但是不杀掉APP，这个时候去设置里面切换语言，然后再打开APP，不会生效，要杀掉APP再打开才可以，像这种小退切换语言的情况是不是没办法处理

**Comment by getActivity** [comment]
小伙子，你先回答我一个问题，App 小退后是什么操作？

**Comment by ender115** [comment]
就是按返回键退出APP，不是杀掉APP，也不是按HOME键，然后打开手机设置，比如在设置中把中文切换到英文，这个时候再打开APP，语言没有切换到英文，还是中文状态

**Comment by ender115** [comment]
我加你的QQ群了，你通过一下啊。到时候在群里沟通更方便

**Comment by getActivity** [comment]
@ender115 小伙子，Github 上面提供的 Demo 有出现这个问题吗？

**Comment by getActivity** [comment]
@ender115 小伙子，QQ 群是禁言状态，通过之后记得直接私信我就行了

**Comment by ender115** [comment]
已解决，多谢大佬
