### ISSUE TITLE
使用setSharedPreferencesName 修改sp文件名 导致切换失效

### ISSUE THREAD

**Issue by truesA** [getActivity/MultiLanguages#13]
使用代码  
MultiLanguages.setSharedPreferencesName("multilanguages");
        // 初始化多语种框架
        MultiLanguages.init(this);
        // 设置语种变化监听器
        MultiLanguages.setOnLanguageListener(new OnLanguageListener() {

            @Override
            public void onAppLocaleChange(Locale oldLocale, Locale newLocale) {
                Log.d("MultiLanguages", "监听到应用切换了语种，旧语种：" + oldLocale + "，新语种：" + newLocale);
            }

            @Override
            public void onSystemLocaleChange(Locale oldLocale, Locale newLocale) {
                Log.d("MultiLanguages", "监听到系统切换了语种，旧语种：" + oldLocale + "，新语种：" + newLocale + "，是否跟随系统：" + MultiLanguages.isSystemLanguage());
            }
        });

1 当前中文或者自动 切换后 比如英文 （或者先选中文 杀死app 然后启动查看是否正确  正确则选择英文杀死 app 启动查看）
2 切多任务杀死程序
3 重新启动 语言没有改变 还是设置之前

**Comment by getActivity** [comment]
小伙子，根据你的描述，我没有复现出来该问题，需要你这边提供一下视频。

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/126286895-cba6b731-5ef5-42ef-a517-7b5d6738455a.png)
