### ISSUE TITLE
BaseFragment的attactContext需要重写吗？

### ISSUE THREAD

**Issue by Ives88** [getActivity/MultiLanguages#14]
看你指南里也没说要重写Fragment里的回调。但我在自己代码里就是要重写才有效，请确认一下？

**Comment by getActivity** [comment]
小伙子，我不知道你说的 BaseFragment 是什么？但是 app 包或者 androidx 包下的 Fragment 是没有 attactContext 这个方法的。

**Comment by Ives88** [comment]
是onAttach(Context)这个方法哈，明白这意思就行了嘛，非得我照着代码敲出来。。。就是在fragment需不需要重写这个方法，传入新的context？

**Comment by getActivity** [comment]
小伙子，麻烦你描述问题的时候一定要详细清晰，不要让我猜这是什么，我没有办法跟你自己的想法来转换我的想法。

**Comment by getActivity** [comment]
还有 Fragment onAttach 方法中 Context 不是 Activity 对象？只要你的 Activity attachBaseContext 方法重写了就可以了，理论上 Fragment 是不需要重写onAttach(Context) 这个方法的。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。
