### ISSUE TITLE
关闭网络，切换语言

### ISSUE THREAD

**Issue by Jun1orChan** [getActivity/MultiLanguages#15]
使用Demo，关闭网络，切换语言，demo会关闭再重新打开Activity绑定新的Context，但是WebView此时的内部提示，却是没有按照预期的语言，一直是第一次初始化的语言。今天折腾一天仍然没有找到原因。
![image](https://user-images.githubusercontent.com/20705287/137482780-1bddbcf4-72b6-47ca-a783-ee9b409d2510.png)

**Comment by getActivity** [comment]
小伙子，我试了一下，确实有这个问题，但是我猜测是 WebView 的缓存导致的，和框架本身没有什么关系，还有你不必太纠结，你可以用自定义一个加载错误的布局，在收到加载出错回调的时候将它遮挡住 WebView 即可。

**Comment by getActivity** [comment]
```java
mWebView.setWebChromeClient(new WebChromeClient() {
    @Override
    public void onReceivedTitle(WebView view, String title) {
        super.onReceivedTitle(view, title);
        if ("file:///android_asset/loaderror.html".equals(title)) {
            // 加载出错的标题
        }
    }
});
```

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
