### ISSUE TITLE
切换时配置里面的没有更改

### ISSUE THREAD

**Issue by TangHaiBo1** [getActivity/MultiLanguages#16]
我写在config里面的数据 切换语言并没有跟随改变 其他的都改了

**Comment by getActivity** [comment]
小伙子，你切换语种的时候调的哪句 API ？

**Comment by TangHaiBo1** [comment]
setAppLanguage

**Comment by getActivity** [comment]
那你说的 `写在config里面的数据` 是什么意思？

**Comment by TangHaiBo1** [comment]
val assetDetail = listOf(
        getStringExt(R.string.text_cb),
        getStringExt(R.string.text_tb),
        getStringExt(R.string.text_transfer),
    )
    val assetCharge = listOf(
        getStringExt(R.string.text_qb),
        getStringExt(R.string.text_jxz),
        getStringExt(R.string.text_ywc),
    )
    val assetMention = listOf(
        getStringExt(R.string.text_qb),
        getStringExt(R.string.text_jxz),
        getStringExt(R.string.text_ywc),
        getStringExt(R.string.text_ybh),
    )
写在一个配置类里面
然后在不同的类里面使用

**Comment by getActivity** [comment]
那语种更新后你有没有手动更新这些配置？

**Comment by TangHaiBo1** [comment]
会重新去加载的但是语言没改过来 就是一些定义好的名称 搞成一个数组直接复用用

**Comment by getActivity** [comment]
@TangHaiBo1 既然切换语种去重新加载了，那为什么没有改过来？

**Comment by TangHaiBo1** [comment]
母鸡啊 当前页面别的都改过来了 就是这个数组里面的没有改过来  写在当前页面内就能改过来

**Comment by getActivity** [comment]
小伙子，你自己都不知道，那你还想我怎么帮你？

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/145556356-7775c502-9944-4f63-a042-43c998404640.png)

**Comment by getActivity** [comment]
小伙子，要不这样，你先排查一下是什么问题导致的，如果确认是框架的问题欢迎你再来找我。

**Comment by getActivity** [comment]
先这样吧，issue 我先关闭了。
