### ISSUE TITLE
与autosize冲突，导致屏幕适配问题

### ISSUE THREAD

**Issue by 13297063206** [getActivity/MultiLanguages#19]
写一大堆，结果网不行提交不了，就是使用了这个库之后，我设置手机固定横屏，获取屏幕宽高混乱，经常数据反着来，比如说1920*1080的手机，有时候是1080*1920，去掉这个库，获取的是固定的1920*1080，导致屏幕适配有问题，小米9，安卓10，库是最新版本，你是怎么处理，是不是库里面有影响获取屏幕宽高的设置

**Comment by getActivity** [comment]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/28616817/160243738-852711bd-fe7d-48c7-b259-d05d2bb93d79.png">
