### ISSUE TITLE
与autosize冲突

### ISSUE THREAD

**Issue by 13297063206** [getActivity/MultiLanguages#20]
## 问题描述

* 框架版本：8.0

* 问题描述：使用这个库会导致autosize的屏幕适配出现问题，我的手机宽高是1080*1920，设置横屏后应该是1920*1080，但是使用这个库之后我获取的宽高是混乱的，有时是1920*1080，有时是1080*1920，导致适配不稳定
* 复现步骤：写一个mainactivity，设置横屏，多次运行app，获取宽高，会发现获取宽高混乱

* 是否必现：是

* 手机信息：小米 9 / Android 10

## 请回答

* 是部分机型还是所有机型都会出现：应该是全部

* 框架最新的版本是否存在这个问题：是

* 是否已经查阅框架文档还未能解决的：否

* issue 是否有人曾提过类似的问题：否

* 是否可以通过 Demo 来复现该问题：是

## 其他

* 提供报错堆栈（如果有报错的话必填）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/28616817/160320092-4895d6dd-ea63-4b13-bdb0-47c0345877b1.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/28616817/160320103-14729fb7-c667-4408-a2fa-03749d49f976.png">

**Comment by getActivity** [comment]
小伙子，请将修改后的 Demo 打成压缩包上传到这里，我这边做一下测试

**Comment by 13297063206** [comment]
demo上复现不了了，现在是切简体正常，切繁体高度不正常，搞不懂，把demo里面代码放到项目里还是不行，我擦

**Comment by getActivity** [comment]
小伙子，Demo 如果不能复现的话，那只能证明你还没有排查到问题的根本原因，建议你先对问题进行筛查，等把问题确定好了再来找我吧。
