### ISSUE TITLE
语言对比

### ISSUE THREAD

**Issue by YQcharlse** [getActivity/MultiLanguages#21]
MultiLanguages.equalsLanguage(Locale locale1, Locale locale2);
语言对比好像不对  
MultiLanguages.equalsLanguage(Locale.CHINA, Locale.TAIWAN)  true
MultiLanguages.equalsLanguage(Locale.SIMPLIFIED_CHINESE, Locale.TAIWAN)  true

**Comment by getActivity** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/28616817/165910801-1d6f17f6-c2ab-4249-a904-796c4b9b547f.png">
