### ISSUE TITLE
与autosize冲突

### ISSUE THREAD

**Issue by XuanYuan112233** [getActivity/MultiLanguages#24]
问题描述
框架版本：8.0

问题描述：使用这个库会导致autosize的屏幕适配出现问题, 横屏启动，分辨率混乱，一会大一会小

复现步骤：写一个mainactivity，设置横屏，多次运行app，获取宽高，会发现获取宽高混乱

是否必现：是

手机信息：红米 k30 / Android 10

请回答
是部分机型还是所有机型都会出现：应该是全部

框架最新的版本是否存在这个问题：是

是否已经查阅框架文档还未能解决的：是

issue 是否有人曾提过类似的问题：是的

是否可以通过 Demo 来复现该问题：是

其他
提供报错堆栈（如果有报错的话必填）

提供截图或视频（根据需要提供，此项不强制）

提供解决方案（如果已经解决了的话，此项不强制）

**Comment by XuanYuan112233** [comment]
MultiLanguages-master.zip

**Comment by XuanYuan112233** [comment]
[MultiLanguages-master.zip](https://github.com/getActivity/MultiLanguages/files/9016124/MultiLanguages-master.zip)

**Comment by XuanYuan112233** [comment]
demo可以复现，英文、繁体、简体、多次切换，然后退出app。再次进入app继续多次切换操作。就可以复现了

**Comment by getActivity** [comment]
在只使用 MultiLanguages，而不用 AutoSize 的情况下是否也会出现这个问题？

**Comment by getActivity** [comment]
* 还有小伙子，我试了一下你发给我的 Demo，执行切换语种，并打印了宽度和高度，最终发现打印出来的宽度和高度是没有问题的，没有出现你说的获取宽高混乱的情况。

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/28616817/177002354-bcd93827-8e3c-4837-8e00-b9f58e67f78c.png">

**Comment by XuanYuan112233** [comment]
> 

你可以横屏 多次切换尝试，我是多次横屏退出app以后在切换就有了

**Comment by XuanYuan112233** [comment]
只使用 MultiLanguages，去掉AutoSize就没有这个问题了

**Comment by XuanYuan112233** [comment]
好吧，我是在加上AutoSize以后出现的问题Emmmm

**Comment by liangrk** [comment]
横屏后的autosize会有一定概率获取宽高错乱的, 跟这个库没啥关系, 我之前的那个项目实现应用内语言切换也有这个问题(同样是autosize), 不过当时还不知道轮子哥这库, 不然直接梭哈啦
