### ISSUE TITLE
不好意思请教一些问题

### ISSUE THREAD

**Issue by MurasameAya** [getActivity/MultiLanguages#25]
#### 问题描述

* 框架版本【必填】：8.0

* 问题描述【必填】：
 1.这边是在MainActivity使用了MainFragment,然后通过lifecycle.addObserver添加了一些事件监听（截图1）,然后在监听方法里面处理切换语言的时候采用（截图2）的方式，然后app就会关闭，并没有重新启动。
2.有试过更换为recreate的方式，这样的话app就不会关闭。但是对于（截图3）的这种by lazy 的数据则切换语言不会成功。得手动重启app才会切换。
* 复现步骤【必填】：切换语言就会出现

* 是否必现【必填】：是

* 出现问题的手机信息：这里是用雷电的模拟器 

* 出现问题的安卓版本：android版本为7.1.2

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

#### 其他

* 提供截图或视频（根据需要提供，此项不强制）
截图1：
![S6DL_XF)6L34KCKI0LQ2AKH](https://user-images.githubusercontent.com/52487645/206953129-384e21b9-a920-401e-a98d-3c6debb8ddd8.png)
截图2：
![IUZHH V@%}XO}0UU_FUK_AK](https://user-images.githubusercontent.com/52487645/206953226-cc766297-8bc9-42c4-9825-9ef119702662.png)
截图3：
![}$2BHCNBQ@%717MQGGM=~K](https://user-images.githubusercontent.com/52487645/206953750-9d08b6a1-a628-4bb6-9404-65a11651680d.png)

**Comment by getActivity** [comment]
> 1.这边是在MainActivity使用了MainFragment,然后通过lifecycle.addObserver添加了一些事件监听（截图1）,然后在监听方法里面处理切换语言的时候采用（截图2）的方式，然后app就会关闭，并没有重新启动。

* 为什么 Demo 没有出现这个问题，但是你的工程会出现，这个问题排查了吗？

> 2.有试过更换为recreate的方式，这样的话app就不会关闭。但是对于（截图3）的这种by lazy 的数据则切换语言不会成功。得手动重启app才会切换。

* 这种就不属于框架的问题了，需要你自行解决。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
