### ISSUE TITLE
界面出现中英文混杂现象

### ISSUE THREAD

**Issue by 15239545925** [getActivity/MultiLanguages#27]
#### 问题描述

* 框架版本【必填】：api 'com.github.getActivity:MultiLanguages:8.0'

* 问题描述【必填】：应用长时间退出到后台切换到前台，或者开发人员 开启不保留活动选项 重新进入前台APP 界面会出现中英文混杂的情况发生，如果是英文语种进入是正常的，中文语种进入的话就会出现。 
*1. 然后我在代码里进入这个界面后 设置当前的语言见第1张图片
* 2.英文没有问题  中文语种状态下  框架获取到的当前语种是中文  但是我设置中文后  框架监听到切换语种  显示的旧语种是英文 en，
* 并且提示需要重启

* 复现步骤【必填】：中文语种状态 开启不保留活动选项 重新进入页面 

* 是否必现【必填】：1. 开启不保留活动选项是必现  2.应用长时间退出到后台切换到前台是偶现

* 出现问题的手机信息：红米 Note10 Pro

* 出现问题的安卓版本：Android11

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分  身边只有这一台手机

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）
解决方案：经过上面的设置语言  不会出现APP退出进入后的乱码问题  但是不明白为什么监听的日志不对

![image](https://user-images.githubusercontent.com/74692077/210945382-d0de3a8f-1935-447e-a3f5-54d802627f06.png)

![5AR5W9O4Y_UN7LC_HMSGA13](https://user-images.githubusercontent.com/74692077/210945259-7246916f-9e15-4ee8-b2b6-0337accc5381.jpg)
![5J1I}SQS(IYIC9Q9SKKZ~NC](https://user-images.githubusercontent.com/74692077/210945286-73256594-9322-4c46-a966-77a97f818ca0.jpg)

**Comment by getActivity** [comment]
https://user-images.githubusercontent.com/28616817/211179180-303a23a4-4d2c-4f27-b3a9-9d4628a33198.mp4

**Comment by getActivity** [comment]
小伙子，我根据你提供的复现进行了步骤
1. 先开启《不保留任何活动》选项
2. 然后将 App 的语种切换到中文
3. 再返回到其他程序上（这里返回了桌面）
4. 最后再返回 App
通过以上步骤进行复现并不会出现你说的出现中文混杂的情况

**Comment by 15239545925** [comment]
轮子哥你好  我从中文语种切换后台再进来  我打印上次的是中文 然后根据第一个截图的代码进行设置语言，出现了第三张截图里面的日志  监听到旧语种是英文，并且需要重启

**Comment by 15239545925** [comment]
目前 我根据这种方式 用户是看不到中英文混杂的现象了。但是如果我不像第一张截图里面设置的话  界面会有混杂情况。

**Comment by getActivity** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/28616817/211179451-dd002ed4-9797-492d-963e-be0069953c24.png">

**Comment by getActivity** [comment]
小伙子，你确定用 Demo 复现不了这个问题？

**Comment by 15239545925** [comment]
是的 Demo我确实没有复现

**Comment by 15239545925** [comment]
对了轮子哥  我出现中英文混杂的情况  是在一个Activity里  这个页面的下方是fragment  是fragment里面的内容出现的英文，ac里面是中文

**Comment by getActivity** [comment]
> 对了轮子哥 我出现中英文混杂的情况 是在一个Activity里 这个页面的下方是fragment 是fragment里面的内容出现的英文，ac里面是中文

https://github.com/getActivity/MultiLanguages/issues/2

**Comment by 15239545925** [comment]
![image](https://user-images.githubusercontent.com/74692077/211501529-94c85397-a28d-43e6-a116-894020cba3ab.png)
轮子哥 我在基类的Fragment里有这么写。他的问题是主动切换不起作用，我是没有主动切换  APP退出再启动自己切换了

**Comment by getActivity** [comment]
小伙子，请提供一个可以复现该问题的 Demo 给我

**Comment by 15239545925** [comment]
轮子哥 我通过微信私发给您了

**Comment by getActivity** [comment]
已在微信中回复

**Comment by 15239545925** [comment]
轮子哥 您好  我找到问题了  感谢您的耐心回复

**Comment by 15239545925** [comment]
![image](https://user-images.githubusercontent.com/74692077/211710676-a15245b2-77b6-4f06-9d89-5c268716ab0a.png)
因为集成了国外的NFC功能，他们设置了默认语言是英文。所以一直中英混杂。
