### ISSUE TITLE
国际化异常

### ISSUE THREAD

**Issue by billdizl** [getActivity/MultiLanguages#28]
#### 建议收集

* issue 是否有人曾提过类似的问题？否

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】通过该lib设置完国际化,清除缓存,仍旧是国际化后的语言,必须要手动判断 是否是系统语言 ,然后设置MultiLanguages.clearAppLanguage 来实现

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 框架 Bug 请提 Bug issue 单，请勿提建议单

请重新提一个 issue 并纠正以上问题
