### ISSUE TITLE
国际化异常

### ISSUE THREAD

**Issue by billdizl** [getActivity/MultiLanguages#29]
#### 问题描述

* 框架版本【必填】：8.0

* 问题描述【必填】：获取 MultiLanguages.isSystemLanguage()为true,获取到的MultiLanguages.getAppLanguage().getLanguage()与真实的手机语言不符

* 复现步骤【必填】：手机正常安装应用,修改应用设置语言切换按钮(自己应用),切换成比如法国,然后将后台清理缓存数据后,国际化异常问题就出现了,以下为在application进行初始化的代码(调试log),以及打印情况,现实情况也是异常情况,但是通过sdk demo却未能复现,搞不懂:::::
* 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/30317994/215760637-7c495d6f-4ebf-42f4-bd4b-9b5c72b531cc.png">
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/30317994/215760897-888a82cf-2507-44b5-a98c-a9c950fcce99.png">

* 是否必现【必填】：是

* 出现问题的手机信息：realme v15

* 出现问题的安卓版本：安卓12

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：否

**Comment by billdizl** [comment]
清理了数据,不是缓存,相当于重新安装了app的效果

**Comment by getActivity** [comment]
小伙子，你如果无法通过 Demo 进行复现，只能说明你提供的复现步骤有问题，请提供一个能复现的 Demo 工程给到我，你可以拿 Github Demo 去改，也可以自己新建一个 Android Demo 工程。

**Comment by billdizl** [comment]
找到问题了,因为我设置了resConfigs "en", "de", "es","fr","pt"
