### ISSUE TITLE
Local点不出来类似的国家 这个Local 应该如何填写

### ISSUE THREAD

**Issue by 704480904** [getActivity/MultiLanguages#31]
#### 问题描述

*restart = MultiLanguages.setAppLanguage(this, Locale.TRADITIONAL_CHINESE);  冷门语言 如波兰语 捷克语  Local点不出来类似的国家 这个Local 应该如何填写

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
