### ISSUE TITLE
如果一定需要不重启来实现多语言的切换 应该如何修改

### ISSUE THREAD

**Issue by 704480904** [getActivity/MultiLanguages#32]
#### 建议收集

* issue 是否有人曾提过类似的问题？无

* 框架文档是否有提及到此问题？否

* 你觉得框架有什么不足之处？无法通过不重启来实现多语言切换 如果一定需要不重启来实现多语言的切换 应该如何修改

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题（乱写回答）

请重新提一个 issue 并纠正以上问题
