### ISSUE TITLE
android-14 出来了，轮子哥什么时候有时间，可以适配一下呀。

### ISSUE THREAD

**Issue by yangfeng1994** [getActivity/MultiLanguages#35]
#### 建议收集

* issue 是否有人曾提过类似的问题？无

* 框架文档是否有提及到此问题？否

* 你觉得框架有什么不足之处？无

* 你觉得该怎么去完善会比较好？无
*
现在android 14 出来了，并且对国际化做了一系列的修改，轮子哥是否可以考虑支持一下android 14 ，并能直接使用其中的api。

**Comment by getActivity** [comment]
小伙子，我在 [Android 14 的官网](https://developer.android.google.cn/about/versions/14) 上面没有找到你所说的那种修改。

**Comment by getActivity** [comment]
小伙子，通过查阅 [Android 14 官方的多语种相关资料](https://developer.android.google.cn/guide/topics/resources/app-languages?hl=zh-cn#app-language-settings)，最终发现 Android 14 多语种这块并没有什么改动，你看看是不是这样的？

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
