### ISSUE TITLE
如果多页面，不重启，怎么使用demo里的那种切换效果呢？

### ISSUE THREAD

**Issue by pbaiyy** [getActivity/MultiLanguages#36]
#### 问题描述

* 请描述一下你的疑惑【必填】：如果我app已经打开了多个页面，这时候切换语言我不想重启，怎么让他效果更好，因为demo里只有一个activity，所以直接重启一个activity就行，如果多个activity，是不是使用recreate比较方便？

#### 请回答

* issue 是否有人曾提过类似的问题？无

* 框架文档是否有提及到此问题？无

**Comment by getActivity** [comment]
小伙子，框架的原理是修改 Resources 对象的语种设置，但是不会对已经设置在 View 上的文本做任何修改。

**Comment by getActivity** [comment]
还有另外一个问题，用什么方式重启 Activity 比较好，Demo 其实已经提供了几个方式，你可以参考一下。

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
