### ISSUE TITLE
 修改语言为中文，关闭 demo 再打开， 再次选择 auto 后关闭，修改系统语言为英语再打开显示不对

### ISSUE THREAD

**Issue by niuyidev** [getActivity/MultiLanguages#38]
### 框架版本【必填】

9.0

### 问题描述【必填】

打开 demo 选择中文简体，关闭 demo 重新打开选择 auto，再次关闭，系统设置修改需要为英语，打开 demo auto 显示了中文简体

### 复现步骤【必填】

 1.在 demo 中选择中文简体，杀死 app
2.系统设置页面选择英文
3.再次打开 app 选择 auto
4.再次杀死 app 重新打开，demo appauto 显示中文简体，此时应该是英文才对

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

小米 12，magic3pro

### 出现问题的安卓版本【必填】

Android13

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
https://github.com/getActivity/MultiLanguages/issues/37

**Comment by getActivity** [comment]
@niuyidev 小伙子，你提过的问题，别人已经提过了，请勿重复再提。

**Comment by niuyidev** [comment]
> @niuyidev 小伙子，你提过的问题，别人已经提过了，请勿重复再提。

9.2aar 我试了，这个问题还是存在，9.2 解决了设置页面更语言后 app 没有刷新语言问题，我说的这个问题依然存在

**Comment by niuyidev** [comment]
@getActivity 轮子哥  刚试了最新demo，问题依然存在

**Comment by getActivity** [comment]
@niuyidev 收到，小伙子，我可以复现到问题了，正在排查一下问题的具体原因。

**Comment by getActivity** [comment]
小伙子，问题修复了，你用上面 apk 试试看问题还会出现不？

**Comment by niuyidev** [comment]
@getActivity 轮子哥你发这个apk设置语言后闪退

**Comment by getActivity** [comment]
[MultiLanguages.apk.zip](https://github.com/getActivity/MultiLanguages/files/13646245/MultiLanguages.apk.zip)

**Comment by getActivity** [comment]
@niuyidev 小伙子，问题修复了，你再试试看，如果没有问题的话，你可以用下面这个 aar 包到项目中试一下。

[MultiLanguages-9.3.aar.zip](https://github.com/getActivity/MultiLanguages/files/13646262/MultiLanguages-9.3.aar.zip)

**Comment by getActivity** [comment]
@niuyidev 小伙子，框架远程依赖已经发布，你可以直接更新到 [9.3](https://github.com/getActivity/MultiLanguages/releases/tag/9.3) 版本试一下。

**Comment by niuyidev** [comment]
@getActivity  okok最近忙都没回复

**Comment by getActivity** [comment]
@niuyidev 小伙子，看到你很久没有回复，这个 issue 我先关闭了，如果后续有发现新的问题（在原有的 issue 下回复和提新的 issue 都可以）欢迎再反馈给我。
