### ISSUE TITLE
语言切换错乱

### ISSUE THREAD

**Issue by ChunmingWu** [getActivity/MultiLanguages#4]
我下载代码运行测试了一下，发现以下问题：
1.MultiLanguages Demo   杀掉程序 -> 进入应用 -> 切换语言：有不小概率出现切换错乱的问题，如本来要切换到繁体，实际切成了简体
2.在AndroidProject项目中使用MultiLanguages，发现杀掉程序再次进入应用，应用语言恢复成了系统语言。我拷贝了以前自己写的语言切换代码用到AndroidProject项目中，仍然有杀掉程序再次进入应用，应用语言恢复成了系统语言的问题。

**Comment by getActivity** [comment]
框架版本号是多少，手机的品牌、型号、Android 版本是什么

**Comment by getActivity** [comment]
小伙子，根据你提供的复现步骤，我并不能复现这个问题，能否录个视频过来我看一下

**Comment by getActivity** [comment]
问题已经解决，后续会发布修复版本
