### ISSUE TITLE
[疑惑]：怎么切换阿拉伯语

### ISSUE THREAD

**Issue by traywangjun** [getActivity/MultiLanguages#40]
### 问题描述【必填】

怎么切换阿拉伯语，查看文档与Locale源码发现没有阿语的参数

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="1043" alt="image" src="https://github.com/getActivity/MultiLanguages/assets/28616817/981a8e18-b219-4d86-a944-61d909c53337">
