### ISSUE TITLE
[Bug]：如果使用MultiLanguages.setDefaultLanguage设置了语言的情况下，在Android13版本的应用第一次启动会导致多次初始化

### ISSUE THREAD

**Issue by a483210** [getActivity/MultiLanguages#42]
### 框架版本【必填】

9.0

## 问题复现和描述

在Android13版本如果设置了`MultiLanguages.setDefaultLanguage`会导致应用重启，结果表现为`Application`和`MainActivity`会多次初始化。
具体原因为：`MultiLanguages`下的`init`方法在`TIRAMISU`版本非系统语言的情况下会设置重新`setApplicationLocales`，导致应用被重启
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
    LocaleManager localeManager = application.getSystemService(LocaleManager.class);
    if (localeManager != null) {
        if (isSystemLanguage(application)) {
            localeManager.setApplicationLocales(LocaleList.getEmptyLocaleList());
        } else {
            localeManager.setApplicationLocales(new LocaleList(getAppLanguage(application)));
        }
    }
}
```

## 疑问

因为这个Api是必定会导致应用重启。

我的问题如下：

- 1.这里设置`setApplicationLocales`的原因是什么，是在解决什么问题。
- 2.这个Api可不可以去除，有没有其他Api可以替代。

### 复现步骤【必填】

- 1.打开Demo的`Application`的`static`的`MultiLanguages.setDefaultLanguage`注解
- 2.添加`MainActivity`的`onCreate`的打印日志`Log.i("language", "MainActivity.onCreate " + hashCode());`
- 3.观察控制台，发现日志打印多次并且hashCode不同

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

所有

### 出现问题的安卓版本【必填】

13

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

Android13版本所有

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
<img width="381" alt="image" src="https://github.com/getActivity/MultiLanguages/assets/28616817/a8a82732-e824-47bb-9ac6-08e768b46849">

小伙子，请先回答这个问题。

**Comment by a483210** [comment]
问题在android13上是必现的

**Comment by getActivity** [comment]
小伙子，你确定这是回答了上面的问题？

**Comment by a483210** [comment]
![CleanShot 2024-02-28 at 01 14 10](https://github.com/getActivity/MultiLanguages/assets/6195035/fd18c0f3-32a3-45ee-abf5-259a7647d67b)

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/MultiLanguages/assets/28616817/f7bef8dc-a73c-418a-9d19-406586877ca6">

**Comment by getActivity** [comment]
@a483210 小伙子，根据你提供的复现步骤，我无法复现到此问题。

**Comment by a483210** [comment]
我初略在模拟器上试了下，application没有触发初始化，mainActivity出发了2次

![CleanShot 2024-02-28 at 13 55 46](https://github.com/getActivity/MultiLanguages/assets/6195035/b0773820-ea61-4d4a-abff-5f7eaedc9e4a)
![CleanShot 2024-02-28 at 13 56 37](https://github.com/getActivity/MultiLanguages/assets/6195035/8b313f1d-8b7b-412c-aa7d-1ab23b2e34e2)

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/MultiLanguages/assets/28616817/64129e49-bb1e-464b-bd56-4bc8f39763aa">

**Comment by getActivity** [comment]
小伙子，我又测试了一下，应用启动的时候 Activity 还是只调用一次 `onCreate`，不知道你说的调用两次 `Activity.onCreate` 方法怎么来的。

**Comment by a483210** [comment]
只有应用第一次打开才会有，因为默认是跟随系统，当设置了与系统配置不同的时候才会触发重启。
你看下这个视频，我比较奇怪的是，为什么每次都会触发`Harmful app blocked`，当然这个其实不影响。

https://github.com/getActivity/MultiLanguages/assets/6195035/48f42fb7-e838-4075-823c-f673a536e17f

**Comment by getActivity** [comment]
小伙子，不知道为啥，我试了若干次，都是只会启动一次 Application 和 Activity，每次我都是卸载重装了。

**Comment by getActivity** [comment]
![](https://github.com/getActivity/MultiLanguages/assets/28616817/32108f49-9429-405c-826c-17843b12fd93)

**Comment by a483210** [comment]
你看下你初始化的时候有没有走init下面的`localeManager.setApplicationLocales(new LocaleList(getAppLanguage(application)));`，理论上走了这里不可能不重新初始化的，我这里的确是每次都会复现。

![CleanShot 2024-03-04 at 09 43 45](https://github.com/getActivity/MultiLanguages/assets/6195035/1d85e90a-90b0-4d09-8be7-aca34753d6e3)

**Comment by getActivity** [comment]
没错的，小伙子，我走的代码就是这里。

**Comment by getActivity** [comment]
长时间没有响应，自动关闭此 issue。
