### ISSUE TITLE
[疑惑]：请问是否支持云端下发语言包

### ISSUE THREAD

**Issue by woaimi520** [getActivity/MultiLanguages#44]
### 问题描述【必填】

请问是否支持云端下发语言包，然后能识别语言包并切换  相当于string value 配置在云端的 这样显示字符就可以动态修改了

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
MultiLanguages 是语种切换框架，而不是动态加载语种文件的框架，如果有动态加载后台下发语种的需求，这块涉及到插件化的知识，你可以去了解一下插件化是怎么加载资源的。

**Comment by getActivity** [comment]
长时间没有响应，自动关闭此 issue。
