### ISSUE TITLE
[疑惑]：在使用语种框架切换语言的时候出现文字无法切换

### ISSUE THREAD

**Issue by chen-fuhai** [getActivity/MultiLanguages#48]
### 问题描述【必填】

https://github.com/getActivity/MultiLanguages/assets/64265495/e820da05-b3cc-47d0-a9c5-d4c2893e878c

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
<img width="291" alt="image" src="https://github.com/getActivity/MultiLanguages/assets/28616817/4fff2c6b-0caf-420a-bbe2-0ecad99b257d">

小伙子，你确定这个问题框架的文档上面没有写？

**Comment by chen-fuhai** [comment]
我查到原因，是因为MainActivity在清单文件中设置了android:launchMode="singleTask"导致的，但是没有一个好的解决方法。

**Comment by getActivity** [comment]
@chen-fuhai 你不一定要用 startActivity 的方式来重新创建 Activity，可以尝试用 recreate 方式。

**Comment by chen-fuhai** [comment]
好的，我试试，谢谢
