### ISSUE TITLE
[疑惑]：关于使用SharedPreferences读取存储的问题。

### ISSUE THREAD

**Issue by Hyyzt** [getActivity/MultiLanguages#49]
### 问题描述【必填】

现在存储语言和国家时，使用的是SharedPreferences，但是SharedPreferences由于性能的关系，某些情况下可能会导致ANR。但是我不确定框架内在只存储两个字段时，**是否会有ANR的问题？**
如果有这种问题的话，可否将存储以及读取的这部分功能抽取出来，解耦，让开发者自己去实现，比如使用DataSotre或者MMKV，而不是SharedPreferences。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题：看似回答了问题，但是实际是乱回答

请重新提一个 issue 并纠正以上问题
