### ISSUE TITLE
始终是中文

### ISSUE THREAD

**Issue by 979881765** [getActivity/MultiLanguages#5]
我这咋使用获取的资源文件都是中文呢
设置了资源文件（values-en）
MultiLanguages.getLanguageResources(this, Locale.ENGLISH).getString(R.string.title)
 还是获取的中文

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/104686512-545b8080-5738-11eb-945d-1dfc8aa56313.png)

**Comment by getActivity** [comment]
小伙子，经过测试，没有出现你说的那个问题

**Comment by getActivity** [comment]
麻烦提供一下框架的版本号和出现的问题的 Android 版本

**Comment by 979881765** [comment]
可以了，原因是我手动创建的文件夹不行（values-en）,用as创建的就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "getActivity/MultiLanguages"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 中午1:49
收件人:&nbsp;"getActivity/MultiLanguages"<MultiLanguages@noreply.github.com&gt;;
抄送:&nbsp;"帮网店写好评20到30一单，每天300-500"<960101847@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [getActivity/MultiLanguages] 始终是中文 (#5)





 
麻烦提供一下框架的版本号和出现的问题的 Android 版本
