### ISSUE TITLE
[疑惑]：关于使用SharedPreferences读取存储的问题。

### ISSUE THREAD

**Issue by Hyyzt** [getActivity/MultiLanguages#50]
### 问题描述【必填】

现在存储语言和国家时，使用的是SharedPreferences，但是SharedPreferences由于性能的关系，某些情况下可能会导致ANR。但是我不确定框架内在只存储两个字段时，**是否会有ANR的问题**？
如果有这种问题的话，可否将存储以及读取的这部分功能抽取出来，解耦，让开发者自己去实现，比如使用DataSotre或者MMKV，而不是SharedPreferences。
如果没有这个问题的话，请忽略。

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
@Hyyzt 小伙子，你的问题大致可以分为两个，我做依次解答：
1. 第一个问题你都自问自答了，SharedPreferences 在存储数据量小的情况下不会性能问题
2. 第二个问题为什么不抽出来，原因有两个，主要是没有必要，这样做没有什么好处，上面也讲了，另外一个是因为框架的初始化时机很早，在 Application 的 attachBaseContext 方法就调用了，而其他的第三方框架的初始化时机是在 Application 的 onCreate 方法中，如果开放给外层实现，也就意味着涉及到的第三方框架的初始化时机要提前。

**Comment by Hyyzt** [comment]
好的，明白了，感谢解惑。
