### ISSUE TITLE
[Bug]：三星（A60）手机切换部分语言失败（印尼语）

### ISSUE THREAD

**Issue by guozhiqiang123** [getActivity/MultiLanguages#51]
### 框架版本【必填】

9.3

### 问题描述【必填】

标题中的手机，切换语言后，即使recreate Activity也不会生效。

### 复现步骤【必填】

无

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

三星A60

### 出现问题的安卓版本【必填】

10

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

部分机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
无报错
```

### 提供截图或视频

![image](https://github.com/user-attachments/assets/64514c86-2b30-45b6-aae7-0529df194bcf)

### 提供解决方案

无

**Comment by getActivity** [comment]
<img width="297" alt="image" src="https://github.com/user-attachments/assets/96c760fb-44df-4abc-938c-df2c2a54d089">

**Comment by getActivity** [comment]
小伙子，根据你提供的信息，我无法复现到该问题，你需要补充更多的信息协助我复现到该问题。

**Comment by guozhiqiang123** [comment]
已解决了。是因为多语言在打包的时候被分割了。需要如下配置：
```kotlin
android {
    bundle {
        language {
            // 不拆分多语言，因为app里面有强制设置多语言的功能
            enableSplit = false
        }
    }
}
```
部分手机印尼语放在values-id下是不行的，要么在values-id-rID也放一份，要么在values-in下放一份也会生效。

**Comment by getActivity** [comment]
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/80916d58-7466-47b7-a7fc-2aec77da1814">

**Comment by getActivity** [comment]
<img width="397" alt="image" src="https://github.com/user-attachments/assets/9b8e0db6-e130-47ec-a2ff-17f3bd1e88f2">

@guozhiqiang123 这个问题答案不是赫然在文档上面写了，你提问题的时候究竟有没有认真看文档？
