### ISSUE TITLE
[Bug]：

### ISSUE THREAD

**Issue by liuwen370494581** [getActivity/MultiLanguages#53]
### 框架版本【必填】

9.3

### 问题描述【必填】

使用作者最新的Demo，然后切换英文，退出app，app名称依然是中文

### 复现步骤【必填】

打开作者的Demo，点击语言切换，切换到英文，然后返回到桌面 桌面上app的名称依然是中文 请问这种问题怎么解决

### 是否必现【必填】

未选择

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

小米9

### 出现问题的安卓版本【必填】

34

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

目前在在模拟上测试过

### 框架最新的版本是否存在这个问题【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

否

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

https://github.com/user-attachments/assets/d1870b54-ddbd-42c7-a6f0-644ac2786cb0

**Comment by getActivity** [comment]
小伙子，目前此 issue 打回，原因如下：

* 没有严格按照 issue 模板填写

请重新提交 issue，并且严格按照 issue 模板填写
