### ISSUE TITLE
引用第三方库的UI，资源文件也是第三方库也包含了，这时手机系统是英文，启动进去有第三方资源的都是中文！！

### ISSUE THREAD

**Issue by liangjiajiajia** [getActivity/MultiLanguages#6]

**Comment by liangjiajiajia** [comment]
给你一个库试下，implementation 'com.github.donkingliang:ImageSelector:1.9.2'，地址：https://github.com/donkingliang/ImageSelector

**Comment by getActivity** [comment]
你有没有重写第三方库的 Activity 中的 attachBaseContext 方法

**Comment by liangjiajiajia** [comment]
![image](https://user-images.githubusercontent.com/38244513/104899828-4ca90f80-59b6-11eb-8ea5-c5a5d8eaa5da.png)
这样调用，第三方的activity我改不了吧。我自己写activity是改了的

**Comment by getActivity** [comment]
小伙子，我这边也改不了

**Comment by getActivity** [comment]
建议你把第三方库的代码拷贝下来

**Comment by getActivity** [comment]
小伙子，问题我这几天已经想到好的解决方案了，利用 Application.ActivityLifecycleCallbacks 来对第三方库中的 Activity 语种进行适配，相关代码已经更新，你更新一下框架版本即可。

**Comment by liangjiajiajia** [comment]
厉害了，先赞一个，稍后验证一下

**Comment by liangjiajiajia** [comment]
厉害了，先赞一个，稍后验证一下

**Comment by liangjiajiajia** [comment]
可以了，感谢感谢

**Comment by yk007** [comment]
如果第三方库 资源文件只有中文的，是不是还是要copy出来配置多套语言

**Comment by getActivity** [comment]
@yk007 没错的，框架只会帮你切换语种，不能帮你翻译 String 中的文本。
