### ISSUE TITLE
切换语言之后，getApplicationContext()关联的还是旧的语言配置

### ISSUE THREAD

**Issue by lan2000** [getActivity/MultiLanguages#7]
切换语言之后，调用getApplication().getApplicationContext().getResources().getConfiguration().getLocales()返回还是旧的
调用getApplicationContext().getString(resid)获取的还是旧语言的字符串

**Comment by getActivity** [comment]
经过核实，确实存在这个问题，已经修复此问题。

**Comment by getActivity** [comment]
[languages.zip](https://github.com/getActivity/MultiLanguages/files/5835959/languages.zip)

**Comment by lan2000** [comment]
能简单说说是啥原因吗，我今天测试了很久。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Android轮子哥"<notifications@github.com&gt;; 
发送时间: 2021年1月19日(星期二) 晚上9:00
收件人: "getActivity/MultiLanguages"<MultiLanguages@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [getActivity/MultiLanguages] 切换语言之后，getApplicationContext()关联的还是旧的语言配置 (#7)





 
languages.zip

**Comment by lan2000** [comment]
我调试的时候也发现了，添加resources.updateConfiguration(config, resources.getDisplayMetrics());&nbsp;&nbsp;
全局application的语言就正常了，不过看文档，这句代码不是过时了吗，用context.createConfigurationContext(config)替换。
我测试也是在安卓10测试。
新API反而有问题，贼郁闷。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Android轮子哥"<notifications@github.com&gt;; 
发送时间: 2021年1月19日(星期二) 晚上9:00
收件人: "getActivity/MultiLanguages"<MultiLanguages@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [getActivity/MultiLanguages] 切换语言之后，getApplicationContext()关联的还是旧的语言配置 (#7)





 
languages.zip

**Comment by lan2000** [comment]
初始设置俄语，主页有webview控件的话，启动的BaseApplication里面onCreate里面设置语言（比如俄语）MultiLanguages.setAppLanguage(this,new Locale("ru"));。
&nbsp;进入页面之后，使用getApplicationContext().getResources().getString() 获取的字符串不是刚才设置的俄语。
如果再次设置MultiLanguages.setAppLanguage，则getApplicationContext().getResources().getString()才获取俄语。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Android轮子哥"<notifications@github.com&gt;; 
发送时间: 2021年1月19日(星期二) 晚上9:00
收件人: "getActivity/MultiLanguages"<MultiLanguages@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [getActivity/MultiLanguages] 切换语言之后，getApplicationContext()关联的还是旧的语言配置 (#7)





 
languages.zip

**Comment by getActivity** [comment]
小伙子，关于 WebView 导致 Activity 语种失效这个问题，我已经补充了解决方案的文档在项目主页上，不过你得先更新一下框架版本，感谢小伙子的支持。

**Comment by lan2000** [comment]
😀👍
还有就是既然webview也关注了，干脆再提示旋转屏幕横竖屏导致多语言失效解决

**Comment by getActivity** [comment]
小伙子，手机屏幕旋转我这边已经测试过了，是没有问题的，不信你下载 Demo 试试看
