### ISSUE TITLE
快速横屏竖屏切换之后，多语言设置失效

### ISSUE THREAD

**Issue by lan2000** [getActivity/MultiLanguages#9]
如标题

**Comment by getActivity** [comment]
Demo 有没有这个问题？

**Comment by getActivity** [comment]
小伙子，我这边用 Demo 测试是没有任何问题的

**Comment by lan2000** [comment]
我用之前你发给我的languages.aar 测试就没问题，用最新的6.0就会出现这个问题。demo就一个页面，我再看看弄多几层页面试试。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Android轮子哥"<notifications@github.com&gt;; 
发送时间: 2021年1月28日(星期四) 下午3:11
收件人: "getActivity/MultiLanguages"<MultiLanguages@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [getActivity/MultiLanguages] 快速横屏竖屏切换之后，多语言设置失效 (#9)





 
小伙子，我这边用 Demo 测试是没有任何问题的

**Comment by getActivity** [comment]
小伙子，需要你提供具体的复现步骤，不然我没办法做修复的。

**Comment by getActivity** [comment]
小伙子，能否提供详细的复现步骤？不然的话我就关闭 issue 了

**Comment by lan2000** [comment]
demo没能复现，关了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Android轮子哥"<notifications@github.com&gt;; 
发送时间: 2021年1月28日(星期四) 晚上7:31
收件人: "getActivity/MultiLanguages"<MultiLanguages@noreply.github.com&gt;; 
抄送: "若即若离若迷离"<122775467@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [getActivity/MultiLanguages] 快速横屏竖屏切换之后，多语言设置失效 (#9)





 
小伙子，能否提供详细的复现步骤？不然的话我就关闭 issue 了
